services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: nfl_2025
      POSTGRES_USER: antoniomajstorovic
      POSTGRES_PASSWORD: tisiglup
    ports:
      - "5432:5432"
    volumes:
      - nfl_pgdata:/var/lib/postgresql
      - ./docker/init:/docker-entrypoint-initdb.d

  backend:
    build: .
    image: nfl-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nfl_2025
      SPRING_DATASOURCE_USERNAME: antoniomajstorovic
      SPRING_DATASOURCE_PASSWORD: tisiglup

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  nfl_pgdata:
