services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: nfl_2025
      POSTGRES_USER: antoniomajstorovic
      POSTGRES_PASSWORD: tisiglup
    ports:
      - "5432:5432"
    volumes:
      - nfl_pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

  backend:
    image: nfl-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nfl_2025
      SPRING_DATASOURCE_USERNAME: antoniomajstorovic
      SPRING_DATASOURCE_PASSWORD: tisiglup

volumes:
  nfl_pgdata:
